# https://eth-brownie.readthedocs.io/en/stable/config.html
# CMD settings: https://eth-brownie.readthedocs.io/en/stable/network-management.html

networks:
  default: development
  development: # used for on Github Actions
    cmd_settings:
      port: 8545
      # mnemonic: "${BROWNIE_DEV_MNEMONIC}"
      fork: "https://mainnet.infura.io/v3/${WEB3_INFURA_PROJECT_ID}"
      default_balance: 1000
      unlock: "0x21a31Ee1afC51d94C2eFcCAa2092aD1028285549" # account with lots of DAI, can also be a list of accounts

compiler:
  solc:
    version: 0.8.7
    remappings:
      # - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.5.0"
      # - "@uniswap=Uniswap/v2-core@1.01"
dependencies:
  # - OpenZeppelin/openzeppelin-contracts@2.5.0
  # - Uniswap/v2-core@1.01
